spring:
   application:
         name: spring Testing
   datasource:
    url: jdbc:postgresql://host.docker.internal:5432/
    username: postgres
    password: 786@admin
    driver-class-name: org.postgresql.Driver
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: update
      show-sql: true
   devtools:
      restart:
         enabled: true
      livereload:
         enabled: true